
test: 
  num_runs: 1     # Number of test runs (set to 1 for single run)
  save_pcd: false  # Save aligned point clouds
  save_error_pcd: false  # Save error visualization point clouds
  visualize: false  # Enable visualization

# Output Options
output:
  save_csv: true  # Save iteration details to CSV
  save_summary: true  # Save summary to TXT
  save_statistics: true  # Save statistics for multiple runs

# File Paths
# environment_cloud_shifted_cylinder measured_cloud_shifted_cylinder
# measured_cloud_parallel_planes environment_cloud_parallel_planes
paths:
  folder_path: "/home/xchu/Downloads/ltloc-results/simulated_pc/shifted_cylinder/"
  output_folder: "/home/xchu/my_git/DCReg/DCReg/dataset/icp_results/"
  source_pcd: "measured_cloud_shifted_cylinder.pcd"
  target_pcd: "measured_cloud_shifted_cylinder.pcd"


# ICP Parameters
icp:
  search_radius: 1.0
  max_iterations: 30
  error_threshold: 0.2  # Error threshold for color visualization (m)

  CONVERGENCE_THRESH_TRANS: 1e-3
  CONVERGENCE_THRESH_ROT: 1e-4

  normal_nn: 5

# Initial Pose Noise (added to ground truth)
initial_noise:
  # x: 0.2
  # y: 0.8
  # z: 0.5
  # roll_deg: 0.
  # pitch_deg: 0.
  # yaw_deg: 2.0
  x: 0.01
  y: 0.01
  z: 0.01
  roll_deg: 0.
  pitch_deg: 0.
  yaw_deg: 0


# Ground Truth (if known, otherwise set to identity)
gt_pose:
  x: 0.0
  y: 0.0
  z: 0.0
  roll_deg: 0.0
  pitch_deg: 0.0
  yaw_deg: 0.

# Degeneracy Thresholds
degeneracy:
  condition_threshold: 10.0  # DEGENERACY_THRES_COND
  eigenvalue_threshold: 120.0  # DEGENERACY_THRES_EIG

# Method-specific Parameters
method_params:

  # Standard Regularization (Tikhonov)
  standard_reg:
    gamma: 100.0  # STD_REG_GAMMA

  # Preconditioned CG
  pcg:
    kappa_target: 10.0  # KAPPA_TARGET
    tolerance: 1e-6  # PCG_TOLERANCE
    max_iter: 10  # PCG_MAX_ITER

  # Truncated SVD
  tsvd:
    singular_threshold: 120.0  # TSVD_SINGULAR_THRESH

  # Solution Remapping (LOAM)
  solution_remapping:
    eigen_threshold: 120.0  # LOAM_EIGEN_THRESH


# XICP Parameters
icp_params:
  # X-ICP specific parameters
  XICP_ENOUGH_INFO_THRESHOLD: 300.0      # 足够信息的阈值
  XICP_INSUFFICIENT_INFO_THRESHOLD: 150.0 # 信息不足的阈值
  XICP_HIGH_INFO_THRESHOLD: 1000.0       # 高信息量阈值
  XICP_SOLUTION_REMAPPING_THRESHOLD: 120.0 # Solution Remapping的特征值阈值
  XICP_MINIMAL_ALIGNMENT_ANGLE: 60.0     # 最小对齐角度（度）
  XICP_STRONG_ALIGNMENT_ANGLE: 45.0      # 强对齐角度（度）
  XICP_INEQUALITY_BOUND_MULTIPLIER: 100.0  # 不等式约束乘数


# Test Methods Configuration
# Format: method_name: [detection_method, handling_method]
test_methods:
#  "None": [ "NONE_DETE", "NONE_HAND" ]
  #  "O3D": [ "O3D", "O3D" ]
  "ME-SR": [ "FULL_EVD_MIN_EIGENVALUE", "SOLUTION_REMAPPING" ]
  "ME-TSVD": [ "FULL_EVD_MIN_EIGENVALUE", "TRUNCATED_SVD" ]
  "ME-TReg": [ "FULL_EVD_MIN_EIGENVALUE", "STANDARD_REGULARIZATION" ]
  "FCN-SR": [ "FULL_SVD_CONDITION", "SOLUTION_REMAPPING" ]
  ##    "CN-SR": [ "EVD_SUB_CONDITION", "SOLUTION_REMAPPING" ]
#  "XICP-1": [ "XICP_SOLUTION_REMAPPING", "XICP_PROJECTION" ]
#  "XICP-EQ": [ "XICP_EQUALITY", "XICP_CONSTRAINT"]
#  "XICP-INQ": [ "XICP_INEQUALITY", "XICP_CONSTRAINT"]
#  "XICP-OP": [ "XICP_OPTIMIZED_EQUALITY", "XICP_PROJECTION"]
#  "XICP-4": [ "XICP_INEQUALITY", "XICP_CONSTRAINT"]
  "XICP": [ "XICP_INEQUALITY", "XICP_CONSTRAINT"]
#  "SuperLoc": [ "SUPERLOC", "SUPERLOC" ]
  # "Ours": [ "SCHUR_CONDITION_NUMBER", "PRECONDITIONED_CG" ]

